# Generated by Django 5.0.3 on 2025-09-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FA", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invited_talks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faculty", models.CharField(max_length=100)),
                ("type_of_event", models.CharField(max_length=100)),
                ("name_of_event", models.CharField(max_length=500)),
                ("duration", models.CharField(max_length=100)),
                ("venue", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("topic_of_talk", models.CharField(max_length=100)),
                ("academic_year", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SDP_organised",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_coord", models.CharField(max_length=1000)),
                ("type_of_event", models.CharField(max_length=100)),
                ("name_of_event", models.CharField(max_length=200)),
                ("duration", models.CharField(max_length=100)),
                ("no_of_participants", models.IntegerField()),
                ("resource_persons", models.CharField(max_length=1000)),
                ("sponsors", models.CharField(max_length=200)),
                ("academic_year", models.CharField(default=2025, max_length=100)),
            ],
        ),
    ]
